export const logos = [
  [
    { url: "/skillLogos/Logo1.svg", name: "Javascript" },
    { url: "/skillLogos/Logo2.svg", name: "Typescript" },
    { url: "/skillLogos/Logo3.svg", name: "React" },
    { url: "/skillLogos/Logo4.svg", name: "Next.js" },
    { url: "/skillLogos/Logo5.svg", name: "Node.js" },
    { url: "/skillLogos/Logo6.svg", name: "Express.js" },
    { url: "/skillLogos/Logo7.svg", name: "Nest.js" },
    { url: "/skillLogos/Logo8.svg", name: "Socket.io" },
    { url: "/skillLogos/Logo9.svg", name: "PostgreSQL" },
    { url: "/skillLogos/Logo10.svg", name: "MongoDB" },
    { url: "/skillLogos/Logo11.svg", name: "Sass/Scss" },
    { url: "/skillLogos/Logo12.svg", name: "Tailwindcss" },
    { url: "/skillLogos/Logo13.svg", name: "Figma" },
    { url: "/skillLogos/Logo14.svg", name: "Cypress" },
    { url: "/skillLogos/Logo15.svg", name: "Storybook" },
    { url: "/skillLogos/Logo16.svg", name: "Git" },
  ],
];
