import {
  Logo1,
  Logo2,
  Logo3,
  Logo4,
  Logo5,
  Logo6,
  Logo7,
  Logo8,
  Logo9,
  Logo10,
  Logo11,
  Logo12,
  Logo13,
  Logo14,
  Logo15,
  Logo16,
} from "@/components/logos";

export const logos = [
  { url: <Logo1 />, name: "Javascript" },
  { url: <Logo2 />, name: "Typescript" },
  { url: <Logo3 />, name: "React" },
  { url: <Logo3 />, name: "Next.js" },
  { url: <Logo5 />, name: "Node.js" },
  { url: <Logo6 />, name: "Express.js" },
  { url: <Logo7 />, name: "Nest.js" },
  { url: <Logo8 />, name: "Socket.io" },
  { url: <Logo9 />, name: "PostgreSQL" },
  { url: <Logo10 />, name: "MongoDB" },
  { url: <Logo11 />, name: "Sass/Scss" },
  { url: <Logo11 />, name: "Tailwindcss" },
  { url: <Logo13 />, name: "Figma" },
  { url: <Logo14 />, name: "Cypress" },
  { url: <Logo15 />, name: "Storybook" },
  { url: <Logo16 />, name: "Git" },
];
